name: Build Release

on:
  push:
    branches: [ staging ]
    paths:
      - 'app/**'
      - 'gradle/**'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'settings.gradle.kts'
      - '.github/workflows/buildRelease.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build new Release Apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
          
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.0.3'

      - name: Setup Ninja
        run: sudo apt-get install ninja-build

      - name: Ninja Version
        run: ninja --version

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28c

      - name: Get Commit Message
        id: commitMessage
        env:
          FULL_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "message=${FULL_MSG%%$'\n'*}" >> $GITHUB_OUTPUT

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: temurin

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache build cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.ccache
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-build-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-cache-

      - name: File Permissions
        run: chmod +x gradlew

      - name: Accept Preview SDK License
        run: echo -n -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > /usr/local/lib/android/sdk/licenses/android-sdk-preview-license

      - name: Build apk
        id: buildAllApks
        uses: gradle/actions/setup-gradle@v4
        with:
            gradle-version: wrapper
      - name: AssembleRelease the project
        run: ./gradlew assembleRelease

      - name: Get JSON
        id: metadataJson
        run: |
          content=`cat app/build/outputs/apk/release/output-metadata.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=json::$content"

      - name: List files
        run: ls app/build/outputs/apk/release

      - name: Sign artifact
        id: signArtifact
        uses: ilharp/sign-android-release@v2
        with:
          releaseDir: app/build/outputs/apk/release
          keyAlias: ${{ secrets.KEYALIAS }}
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: '36.0.0'

      - name: List files
        run: ls app/build/outputs/apk/release

      - name: Rename APK
        run: mv app/build/outputs/apk/release/app-release-unsigned-signed.apk app/build/outputs/apk/release/app-release.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release Artifact
          path: app/build/outputs/apk/release/app-release.apk


      - name: Print json
        run: echo ${{ github.event.head_commit }}

      - name: Send Notification
        continue-on-error: true
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://fcm.googleapis.com/fcm/send'
          method: 'POST'
          customHeaders: '{"Authorization":"key=${{ secrets.FCM_KEY }}"}'
          data: '{"to": "/topics/update-v3-release","data": {"version": ${{ fromJson(steps.metadataJson.outputs.json).elements[0].versionCode }},"type": "update","notification": {"body": "Update available. ${{ steps.commitMessage.outputs.message }}","title": "Update"}}}'

      - name: Send Telegram message
        run: "curl --location --request POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' --header 'Content-Type:application/json' --data-raw '{\"chat_id\":\"${{ secrets.TELEGRAM_TO_MAIN }}\",\"message_thread_id\":${{ secrets.TELEGRAM_MAIN_TOPIC_ID }},\"text\":\"#A12\\n**staging**\\n\\ncommit: `${{ github.event.head_commit.message }}` [${{ github.event.head_commit.id }}](${{ github.event.head_commit.url }})\",\"parse_mode\":\"markdown\",\"reply_markup\":{\"inline_keyboard\":[[{\"text\":\"Latest Android 12+\",\"url\":\"https://github.com/DerTyp7214/RboardThemeManagerV3/releases/download/${{ fromJson(steps.metadataJson.outputs.json).elements[0].versionName }}/app-release.apk\"}]]}}'"

      - name: Send Telegram message
        run: "curl --location --request POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' --header 'Content-Type:application/json' --data-raw '{\"chat_id\":\"${{ secrets.TELEGRAM_TO_MAIN }}\",\"message_thread_id\":${{ secrets.TELEGRAM_MAIN_TOPIC_ID_DEBUG }},\"text\":\"#A12\\n**staging**\\n\\ncommit: `${{ github.event.head_commit.message }}` [${{ github.event.head_commit.id }}](${{ github.event.head_commit.url }})\",\"parse_mode\":\"markdown\",\"reply_markup\":{\"inline_keyboard\":[[{\"text\":\"Download Android 12+\",\"url\":\"https://github.com/DerTyp7214/RboardThemeManagerV3/releases/download/${{ fromJson(steps.metadataJson.outputs.json).elements[0].versionName }}/app-release.apk\"}]]}}'"

      - name: Upload Assets
        id: upload_assets
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest-release
          prerelease: false
          title: Rboard Manager Release ${{ fromJson(steps.metadataJson.outputs.json).elements[0].versionName }}
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/apk/release/output-metadata.json


      - name: Create new Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ fromJson(steps.metadataJson.outputs.json).elements[0].versionName }}
          prerelease: false
          title: Rboard Manager Release ${{ fromJson(steps.metadataJson.outputs.json).elements[0].versionName }}
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/apk/release/output-metadata.json
