name: Build Debug

on:
  push:
    branches: [ master ]
    paths:
      - 'app/**'
      - 'gradle.properties'
      - '.github/workflows/buildDebug.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Print json
        run: IN="${{ github.event.head_commit.message }}" && arrIN=(${IN%%$'\n'*}) && echo ${arrIN[0]} && false

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache build cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.ccache
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-build-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-cache-

      - name: Build apk
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleDebug

      - name: Get JSON
        id: metadataJson
        run: |
          content=`cat app/build/outputs/apk/debug/output-metadata.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=json::$content"

      - name: List files
        run: ls app/build/outputs/apk/debug

      - name: Sign artifact
        id: signArtifact
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/debug
          alias: ${{ secrets.KEYALIAS }}
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: 30.0.3

      - name: List files
        run: ls app/build/outputs/apk/debug

      - name: Delete old APK
        run: rm app/build/outputs/apk/debug/app-debug.apk

      - name: Rename APK
        run: mv app/build/outputs/apk/debug/app-debug-signed.apk app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Debug Artifact
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Send Notification
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://fcm.googleapis.com/fcm/send'
          method: 'POST'
          customHeaders: '{"Authorization":"key=${{ secrets.FCM_KEY }}"}'
          data: '{"to": "/topics/update-v3-debug","data": {"version": ${{ fromJson(steps.metadataJson.outputs.json).elements[0].versionCode }},"type": "update","notification": {"body": "Update available. ${{ github.event.head_commit.message }}","title": "Update"}}}'

      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: "commit: `${{ github.event.head_commit.message }}` [${{ github.event.head_commit.id }}](${{ github.event.head_commit.url }})"
          document: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Assets
        id: upload_assets
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest-debug
          prerelease: true
          title: Rboard Manager Development ${{ fromJson(steps.metadataJson.outputs.json).elements[0].versionName }}
          files: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/debug/output-metadata.json

      - name: Create new Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ fromJson(steps.metadataJson.outputs.json).elements[0].versionName }}-debug
          prerelease: true
          title: Rboard Manager Development ${{ fromJson(steps.metadataJson.outputs.json).elements[0].versionName }}
          files: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/debug/output-metadata.json
